    # - name: Remove old container if exists
    #   community.docker.docker_container:
    #     name: "{{ container_name }}"
    #     state: absent

    # - name: Remove an old volume if exists
    #   community.docker.docker_volume:
    #     name: "{{ volume_name }}"
    #     state: absent

    - name: Validate the activity
      assert:
        that: 
          - pathfinder_api_token  != 'not_defined'
        fail_msg: "Invalid activity provided, specify one of- nuke, touch, copy"
        success_msg: "Input looks good!"
    
    - block:
        - name: 'Print message about the problem'
          debug:
            msg: API Token not defined

        - name: 'Finish processing'
          meta: end_host
      when: pathfinder_api_token  == 'not_defined'

    - name: Git checkout
      ansible.builtin.git:
        repo: '{{ pathfinder_git_link }}'
        dest: "{{ pathfinder_git_name }}/"
        version: "{{ pathfinder_version }}"

      

          