- name: Install Starkent node
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes
  
  tasks:

    - name: Run main task
      include_tasks: "main_starknet_init.yml"
      