- name: Remove node
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes    
  
  tasks:
 

      - name: Get info on docker host and list images matching the filter
        docker_host_info:
          containers: yes
          containers_filters:
            label: "{{label_name}}={{label_value}}"
        register: result

      - name: Remove old container if exists
        community.docker.docker_container:
          name: '{{ item.Names[0] }}'
          state: absent
        loop: "{{ result.containers }}"


    
      - name: Prune everything
        community.docker.docker_prune:
          containers: true
          images: true
          images_filters:
            dangling: false
          networks: true
          volumes: true
          builder_cache: true

      - name: Remove Git directory
        ansible.builtin.file:
          path: "{{ pathfinder_git_name }}/"
          state: absent

      




