- name: Install 
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes    
  
  tasks:
    
      
      - name: Get info on docker host and list images matching the filter
        docker_host_info:
        images: yes
        images_filters:
          label: "eqlabs/pathfinder"
        register: result

      - debug:
          var: result.host_info  