- name: Install 
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes    
  
  tasks:
    
      
      - name: Get info on docker host and list images matching the filter
        docker_host_info:
          containers: yes
          containers_filters:
            label: org.opencontainers.image.title=pathfinder
        register: result

      # - name: save the Json data to a Variable as a Fact
      #   set_fact: 
      #     jsondata: "{{ result.containers | from_json }}"


      # - name: Containers Names
      #   set_fact:  
      #     containernames:  "{{ jsondata | json_query(jmesquery) }}"
      #   vars:
      #     jmesquery: 'containers[*].names'

      # - name: Print all containers names
      #   debug: 
      #     msg: "{{ item }}"
      #   with_items: 
      #   - "{{ containernames }}"
      

      - name: Print current version of the container
        debug:
          msg: "{{ item.Names[0]}}"
        loop: "{{ result.containers }}"

      - name: Remove old container if exists
        community.docker.docker_container:
          name: '{{ item.Names }}'
          state: absent
        loop: "{{ result.containers }}"

