- name: Install 
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes    
  
  tasks:
    
      
      - name: Get info on docker host and list images matching the filter
        docker_host_info:
          containers: yes
          containers_filters:
            label: org.opencontainers.image.title=pathfinder
        register: result

      - debug:
          var: result.host_info  