- name: Install 
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes    
  
  tasks:
    
      
      - name: Get info on docker host and list images matching the filter
        docker_host_info:
          containers: yes
          containers_filters:
            label: "{{label_name}}={{label_value}}"
        register: result


      - name: Print current version of the container
        debug:
          msg: "{{ item.Names[0]}}"
        loop: "{{ result.containers }}"

      - name: Remove old container if exists
        community.docker.docker_container:
          name: '{{ item.Names[0] }}'
          state: absent
        loop: "{{ result.containers }}"

      - name: Prune everything
        community.docker.docker_prune:
          containers: true
          images: true
          networks: true
          volumes: true
          builder_cache: true

